let tasks = [
    {
        id: 0,
        category: "todo",
        title: "Putzen",
        description: "nicht nur sauber, sondern rein",
        priority: "urgent",
        workers: ["w2", "w1", "w3"],
        type: "User Story",
    },
    {
        id: 1,
        title: "Omas über die Straße helfen",
        category: "progress",
        description: "auch wenn sie nicht wollen",
        priority: "medium",
        workers: ["ct", "aq", "eh"],
        type: "User Story",
    },
    {
        id: 2,
        title: "Schokolade aufessen",
        category: "await",
        description:
            '... issue ist "onhold" da immer wieder neue Schokolade geliefert wird',
        priority: "medium",
        workers: ["ct", "aq", "eh"],
        type: "Technical Task",
    },
    {
        id: 3,
        title: "Hirn benutzen",
        category: "await",
        description: "morgen vielleicht",
        priority: "medium",
        workers: ["ct", "aq", "eh"],
        type: "Technical Task",
    },
    {
        id: 4,
        title: "krasse Sachen machen",
        category: "done",
        description: "die Nachbarn gegrüßt",
        priority: "urgent",
        workers: ["ct", "aq"],
        type: "User Story",
    },
    {
        id: 5,
        title: "Schäfchen zählen",
        category: "progress",
        description:
            "Wenn Schäfchen Schäfchen zählen, zählen sie sich dann mit? ",
        priority: "low",
        workers: ["ct", "aq", "eh"],
        type: "Technical Task",
    },
];