/*
nickname wird nicht mehr benötigt
users und allUsers mergen
farben über eine Schleife vergeben 0-14 und dann wieder bei 0 anfangen
*/
const allUsers = [
  { 
    id: 0,
    firstname: 'guest',
    personalColor: 'var(--color-grey)',
    projectId: [0],
  },

  {
    id: 1,
    firstname: 'Christina',
    familyname: 'Troitzsch',
    email: 'christina@troitzsch.de',
    phone: '+49 177 2632522',
    pword: '*****',
    personalColor: 'var(--color-yellowgreen)', // farbe Logik vergeben?
    projectId: [1],
  },
  {
    id: 2,
    firstname: 'Erwin',
    familyname: 'Hoermann',
    pword: '*****',
    email: 'ere02@bavarian.de',
    phone: '+49 1999 20202020',
    personalColor: 'var(--color-fuchsia)',
    projectId: [1],
  },
  {
    id: 3,
    firstname: 'Ardit',
    familyname: 'Qoku',
    pword: '*****',
    email: 'ardit@Qoku.de',
    phone: '+49 59 111111111',
    personalColor: 'var(--color-blue)',
    projectId: [1],
  },
  {
    id: 4,
    firstname: 'Cleo',
    familyname: 'Patra',
    pword: '*****',
    email: 'cleopatra@egypt.eg',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-lila)',
    projectId: [1],
  },
  {
    id: 5,
    firstname: 'T.',
    familyname: 'EstUser',
    pword: '*****',
    email: 't.estuser@web.de',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-redorange)',
    projectId: [1],
  },
  {
    id: 6,
    firstname: 'Test',
    familyname: 'User',
    pword: '*****',
    email: 'test@user.de',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-dark-cyan)',
    projectId: [1],
  },
  {
    id: 7,
    firstname: 'User',
    familyname: 'Test',
    pword: '*****',
    email: 'user.test@gmx.de',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-yelloworange)',
    projectId: [1, 2],
  },
  {
    id: 8,
    firstname: 'U.',
    familyname: 'Test',
    pword: '*****',
    email: 'u.test@yahoo.de',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-violett)',
    projectId: [1, 2],
  },
  {
    id: 9,
    firstname: 'Tess',
    familyname: 'Tuser',
    pword: '*****',
    email: 'tess.tuser@gmail.com',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-aquamarin)',
    projectId: [1, 2],
  },
  {
    id: 10,
    firstname: 'Testu',
    familyname: 'Ser',
    pword: '*****',
    email: 'test34@googlemail.de',
    phone: '+49 199 99999999',
    personalColor: 'var(--color-cyan)',
    projectId: [1],
  }
];

